owner: h-lopez
repo: status.hlnet.us

sites:
  - name: hlnet.us
    showAverageResponseTime: false
    url: https://hlnet.us
  - name: plex.hlnet.us
    showAverageResponseTime: false
    url: https://plex.hlnet.us
    expectedStatusCodes:
      - 401
  - name: requests.hlnet.us
    showAverageResponseTime: false
    url: https://requests.hlnet.us

status-website:
  cname: status.hlnet.us
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: hlnet.us - System Health
  # introTitle: hlnet.us System Health
  # introMessage: service status
  theme: light
  navbar:
    - title: HLnet
      href: https://hlnet.us
    - title: Status
      href: /

i18n:
  # disable footer
  footer: ''
